@Library('jenkins-shared-library') _

def configmap = [
    project: "expense"
    component: "backend"
]

if( ! env.BRANCH_NAME.equalsIgnoreCase('main')){
    nodeJSEKSPipeline(configMap)
}
else{
    echo "follow the processof PROD"
}