pipeline{
    agent{
        label 'AGENT-1'
    }
    options{
        disableConcurrentBuilds()

    }
    environment{
        appVersion = ''
        region = 'us-east-1'
        account_id = '767397679511'
        project = 'expense'
        environment = 'dev'
        component = 'backend'
    }
    stages{
        stage('version check') {
            steps{
                script{
                            def packageJson = readJSON file: 'backend/package.json'
                            appVersion = packageJson.version
                            echo "App version: ${appVersion}"

                }
            }
        }
        stage('Deocker build'){
            steps{
                withAWS(region: 'us-east-1', credentials: 'aws-creds'){
                    sh """
                        cd backend
                        aws ecr get-login-password --region ${region} | docker login --username AWS --password-stdin ${account_id}.dkr.ecr.us-east-1.amazonaws.com
                        docker built -t ${account_id}.dkr.ecr.us-east-1.amazonaws.com/${project}/${environment}/${component}:${appVersion} .
                        docker push ${account_id}.dkr.ecr.us-east-1.amazonaws.com/${project}/${environment}/${component}:${appVersion}
                    """
                }
            }
        }
    }
    post{
        always{
            echo 'This section always run'
            deleteDir()
        }
        failure{
            echo " Build failed"
        }
        success{
            echo "Build run successfully"
        }
    }
}