pipeline {
    agent {
        label 'AGENT-1'
    }
    options{
        disableConcurrentBuilds()
        timeout( time: 30, unit: 'MINUTES')
        ansiColor('xterm')
    }
    parameters{
        choice(name: 'ACTION', choices: ['apply', 'destroy'], description: 'select action' )
    }
    stages{
        stage('init & apply'){
            steps{
                withAWS( region: 'us-east-1', credentials: 'aws-creds'){
                    sh '''
                        cd 20-security-groups
                        terraform init
                        terraform plan -out=tfplan
                    '''
                }

            }
        }
        stage('Apply or Destroy'){
            input{
                message "Shall we proceed"
                ok "Yes, we should"
            }
            steps{
                withAWS( region: 'us-east-1', credentials: 'aws-creds'){
                    sh """
                        cd 20-security-groups
                        if [ "${params.ACTION}" == "apply" ];
                        then
                            terraform apply -auto-approve tfplan
                        elif [ "${params.ACTION}" == "destroy" ];
                        then
                            terraform destroy -auto-approve
                        fi
                    """
                }
            }
        }
        stage('Apply downstream-1'){
            when {
                expression{ params.ACTION == 'apply' }
            }
            parallel{
                steps{
                    script{
                        build job: '30-sebastian', parameters: [string(name:'ACTION', value:'apply')], wait:false
                    }
                }
                steps{
                    script{
                        build job: '35-rds', parameters: [string(name:'ACTION', value:'apply')], wait:false
                    }
                }
                steps{
                    script{
                        build job: '40-eks', parameters: [string(name:'ACTION', value:'apply')], wait:false
                    }
                }
                
                steps{
                    script{
                        build job: '70-ecr', parameters: [string(name:'ACTION', value:'apply')], wait:false
                    }
                }
                
            }
        }
        stage('Apply downstream-2'){
            when {
                expression{ params.ACTION == 'apply' }
            }
            parallel{
                steps{
                    script{
                        build job: '50-acm', parameters: [string(name:'ACTION', value:'apply')], wait:false
                    }
                }
                steps{
                    script{
                        build job: '60-alb', parameters: [string(name:'ACTION', value:'apply')], wait:false
                    }
                }
                steps{
                    script{
                        build job: '90-cdn', parameters: [string(name:'ACTION', value:'apply')], wait:false
                    }
                }

            }
        }

        // stage('destroy upstream'){
        //     when{
        //         expression{ params.ACTION == 'destroy' }
        //     }
        //     steps{
        //         script{
        //             build job: '00-vpc', parameters: [string(name:'ACTION', value:'destroy')], wait:false
        //         }
        //     }
        // }

    }
    post{
        always{
            echo 'This section always run'
            deleteDir()
        }
        failure{
            echo " Build failed"
        }
        success{
            echo "Build run successfully"
        }
    }
}