configMap:
  db_host: expense-dev.c32swm8ionjr.us-east-1.rds.amazonaws.com
deployment:
  containers:
    imageversion: IMAGE_VERSION
    imageURI: 767397679511.dkr.ecr.us-east-1.amazonaws.com/expense/dev/backend
  replicas: 2

  